fprintf(1,'Executing %s at %s:\n',mfilename(),datestr(now));
ver,
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name(1:5), 'SPM12'),
           spm_jobman('initcfg');
           spm_get_defaults('cmdline', 1);
        end

        jobs{1}.spm.spatial.coreg.estimate.ref = {...
['/home/mariacabello/wf_workspace/thesis_data/func_anat/sub-187232/ses-01/anat/sub-187232_ses-01_run-01_T1w.nii'];...
};
jobs{1}.spm.spatial.coreg.estimate.source = {...
['/home/mariacabello/wf_workspace/thesis_data/fmri2standard/sub-187232/spm_coregister2T1_sbref/sub-187232_ses-01_run-01_rest_sbref_ap_flirt_corrected_coregistered2T1.nii'];...
};
jobs{1}.spm.spatial.coreg.estimate.other = {...
'/home/mariacabello/wf_workspace/thesis_data/fmri2standard/sub-187232/spm_coregister2T1_bold/sub-187232_ses-01_run-01_rest_bold_ap_roi_mcf_corrected_coregistered2T1.nii';...
};
jobs{1}.spm.spatial.coreg.estimate.roptions.prefix = 'r';

        spm_jobman('run', jobs);

        
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;